### ISSUE TITLE
OpenVRTwitchChat merge into OVRDrop?

### ISSUE THREAD

**Issue by Zeks** [Hotrian/OVRdrop-Public#22]
Will this ever happen? At the moment OVR is completely unsuitable for the task so I had to refund...

**Comment by Hotrian** [comment]
> Will this ever happen?

Yes I still have plans for that

> At the moment OVR is completely unsuitable for the task so I had to refund...

Why? You can use OVRdrop to clone the Twitch Popout Chat. It even has the `-twitchmode` launch flag which automatically targets the Twitch Popout Chat and crops the window to the optimal settings. I also have plans to add back a notification sound when you receive a message.

**Comment by Zeks** [comment]
I haven't found an option to scale the appearing window so its immensely huge unlike what OVRTC showed.
It also appears immediately and fully sized, no scale options evident in the interface.
Meaning:  in audioshield if you turn the controller ever so slightly you get a huge white window popping up immediately, where OVRTC will either not trigger or be unnoticeable.
Also, no notification sound.

Also... is this -twitchmode mentioned anywhere on teh faq?

**Comment by Hotrian** [comment]
> I haven't found an option to scale the appearing window so its immensely huge

You can use the controls in the bottom right of the main window to make it huge. If you need the text to physically be larger (and not the overlay itself) select the Twitch Popout Chat and use Ctrl+= to scale up the text in the actual window.

> Meaning: in audioshield if you turn the controller ever so slightly you get a huge white window popping up immediately

What do you mean here? OVRTC and OVRdrop are built on the same base code so they should work the same way.

> Also... is this -twitchmode mentioned anywhere on teh faq?

Sorry, I don't think it is. It's mentioned [in the launch announcement](http://steamcommunity.com/games/586210/announcements/detail/223333117182998322) though.

**Comment by Zeks** [comment]
OVRTC by default shows the chat in a tiny rectangle unless you move controller REALLY close to the face.
This is ideal for games that make you turn it like crazzy and only want to see chat at specific moments.
And I dont need to make anything large, in fact I'd very much like to scale twitch popup window down, it's way too large otherwise

**Comment by Hotrian** [comment]
> OVRTC by default shows the chat in a tiny rectangle unless you move controller REALLY close to the face.

I believe this is the "scale on gaze" option? You can set that up in the bottom right of the OVRdrop main window. You can set the overlay to be very tiny and have it scale up when you look at it.

I'm not sure what you mean by "really close to the face", because OVRTC did not have a distance constraint. It would scale up when you looked directly at it, which may have been difficult from a distance if it was too small, so maybe this is what you mean?

**Comment by Hotrian** [comment]
Also I recommend using "Dark Mode" in the Twitch Popout Chat. Then the background will be a dark color instead of bright white.

**Comment by Zeks** [comment]
I am not sure we are even speaking of the same application. I dont have the screenshots since the app is already refunded but in th bottom right there were just 1 or 2 rectangles completely unrelated to this fucntionality. There definitely wasnt anything about scale on gaze.

**Comment by Hotrian** [comment]
Yes, in the bottom right there's a dropdown that's set to `None` by default but can be set to `Scale, `Alpha` (which is transparency), or `AlphaAndScale`. I will attach screenshots when I get back home.

**Comment by Hotrian** [comment]
Here is the default appearance:

![pic](http://i.imgur.com/GGHDJq4.png)

Here is how it appears using `Alpha`:

![pic2](http://i.imgur.com/Qdv8syt.png)

And I forgot to mention the `DodgeGaze` setting:

![pic3](http://i.imgur.com/sjJjm3Y.png)

`DodgeGaze` causes the Overlay to move to the side when you look at it, and you can configure which direction it moves (Up/Down/Left/Right or Up+Left/Up+Right/Down+Right/Down+Left) and the speed at which it moves.
