### ISSUE TITLE
Youtube Video Missing

### ISSUE THREAD

**Issue by flybers** [Hotrian/OVRdrop-Public#31]
Hi, Nicholas.

Your Youtube Steam promo video has disappeared from Youtube.
As mentioned in the 'Blank White Screen' issue. I intend to feature OVRdrop in our online VR chat show. We intended to show your promo youtube video to our audience.

**Comment by Hotrian** [comment]
Are you talking about the Steam Trailer? I don't believe I ever uploaded a copy to YouTube, but I should have a copy laying around somewhere I could send you directly. 

I know there are a few YouTube channels that take the videos off Steam and re upload them so I wouldn't be surprised if OVRdrop's trailer was on YouTube already.

**Comment by Hotrian** [comment]
So in fact I did not upload a public copy to YouTube. I wasn't able to find any copies floating around YouTube even though I did before. 

[Here's a link](https://youtu.be/99uycwLNpj4) to the unlisted trailer. I believe that version is the final cut used on Steam. I would recommend not using the segment from Tilt Brush you can avoid it - that's the only segment I was worried about YouTube giving me a flag over.

**Comment by Hotrian** [comment]
Hey, I'm going to close this because I assume you got the link I sent you :).

**Comment by flybers** [comment]
Yes. thank you.
