### ISSUE TITLE
Instant Crash with new experimental build

### ISSUE THREAD

**Issue by hammerschaedel** [Hotrian/OVRdrop-Public#34]
newest Nvidia driver, and system fully patched.

hmm , no crash logs generated. It starts the unity splash screen, but the standard gui isn´t generated bevor the unity window closes.

**Comment by Hotrian** [comment]
Can you try restarting Steam?

Also can you attach the `output_log.txt` from the Data folder?

**Comment by hammerschaedel** [comment]
restarting steam fixed it...
[output_log.txt](https://github.com/Hotrian/OVRdrop-Public/files/955735/output_log.txt)
