### ISSUE TITLE
Unable to click with mouse in TeamSpeak 3 or in Windows Onscreen Keyboard

### ISSUE THREAD

**Issue by m33ps** [Hotrian/OVRdrop-Public#35]
Seems like the mouse clicks are not registering in either application.   I have tried all 3 VR Click API's as well as selecting the monitor the app is on as opposed to just the app.  Chrome and other apps seem to register mouse clicks fine.

**Comment by Hotrian** [comment]
Can you try starting Steam as Administrator? That will boot up OVRdrop as Administrator as well. That should fix any permission issues you might be having. 

If OVRdrop has a lower security level than the application, it won't be able to click on it. I know I had issues clicking on Task Manager unless OVRdrop got launched as Admin, so I assume this extends to the On Screen Keyboard as well, and might even fix the issue with TeamSpeak 3.

**Comment by Hotrian** [comment]
Closing as I'm assuming you fixed this long ago and never replied, but if that is not the case feel free to reopen.
