### ISSUE TITLE
Direct mode crashes

### ISSUE THREAD

**Issue by noel4nopun** [Hotrian/OVRdrop-Public#36]
Hey y'all killer app for a moment I was on top of the world I am a sim racer using iracing, this app was a break through for me, opening a door or at least a window to dashboard apps that I could see for the car that the iracing sim doesn't show, everything was working fine but then realized my frame rate dropped to almost 44fps which is in bearabale, I get the best frame rate through iracing using direct mode where the sim sees my Vive vr headset as a second monitor and configured the sim setting to give me the great 89fps, the down side is my headset glitches out and goes completely red when launching ovrdrop when in this mode, any thoughts on a work around I can do to get the window to other apps and my 89fps? Also while I'm asking any way I can get "multiple" windows showing a few other dashboards?

**Comment by Hotrian** [comment]
> my headset glitches out and goes completely red

This sounds like it might be a USB bandwidth issue - that's typically what I see with similar reports. I'm not sure how exactly OVRdrop could be upping the USB bandwidth, but perhaps SteamVR is sending more data when displaying Overlays?

I use this in Direct Mode all the time, so I know it works okay - at least on my hardware.

Can you attach a DxDiag report?

> Also while I'm asking any way I can get "multiple" windows showing a few other dashboards?

Not yet, but hopefully I will be able to add this soon :).

**Comment by noel4nopun** [comment]
Thank you so much for your help, I am really excited to try and get this portal to work, with my custom dashboards.

unfortunately, same thing happened as soon as I go to launch OVRdrop the VR screen goes red, attached is what I hope to be a DxDiag report let me know if I missed anything.

thank you so much for you taking the time to help troubleshoot this with me

[DxDiag.txt](https://github.com/Hotrian/OVRdrop-Public/files/991458/DxDiag.txt)

**Comment by Hotrian** [comment]
Thanks, that is the DxDiag I was looking for.

I noticed you have USB 3.x and 2.0 ports, some USB Controller's 3.x ports aren't up to spec, and the Vive won't like them. If you are using the 3.x ports can you switch the Vive to the 2.0 ports? At the same time, some people are having issues with the 2.0 ports and 3.x work fine, so if you are using 2.0 can you switch to 3.x?

It looks like you're using an Intel USB Controller, and I remember hearing some of the Intel USB Controllers had issues with the Vive - It's possible you may be experiencing this. If switching ports doesn't help, is there any chance I can convince you to buy and try out the [Inateck USB 3.0 Controller](https://www.amazon.com/dp/B00E59W1G8)? This is the one recommended by Valve to fully support the Vive, and seems to fix everyone's Vive issues.

**Comment by noel4nopun** [comment]
thanks for the information I will look more into adding that upgrade...

Turns out after further investigation my red glitch was coming from having only one monitor hooked up, as soon as I added a second monitor to keep the OVR drop screen then the screens I was overlaying on the other monitor everything is working perfectly, too cool of an app I love it so much!...

I have another question but not sure if I should post a new ticket or if its ok to ask in this thread so Im gonna ask anyway...

Is there a way to set a hot key to switch window sources.
I would like to be able to toggle between multiple windows while racing 200 mph

**Comment by Hotrian** [comment]
> Turns out after further investigation my red glitch was coming from having only one monitor hooked up [...]

Very strange! I'm not sure why that would happen :(.

> Is there a way to set a hot key to switch window sources.

Not yet, but I'll be sure to add it to the list of things to do :).

**Comment by Hotrian** [comment]
Still not sure why a second monitor fixed your primary issue, but I'm closing this issue at this time and will be opening a new one re: Hotkey to swap sources
