### ISSUE TITLE
Cannot click in the game Carnival Games VR

### ISSUE THREAD

**Issue by vivalite** [Hotrian/OVRdrop-Public#37]
Hi Hotrian,

I just found out if I open the game Carnival Games VR, OVRdrop click will stop to work. I tried to run the OVRdrop with administrator right (Right click the exe in steam folder and select "run as administrator"), but click still not working. 

It seems Carnival Games VR did some magic trick to intercept the controller events. I can verify the same problem with OVRDDP. It's really strange and google turned out nothing. Could you sheds some light on this issue?

Thanks!

**Comment by Hotrian** [comment]
So unfortunately if this happens specifically in Carnival Games VR, but works in other VR games, it's likely they're calling [IVRSystem::CaptureInputFocus](https://github.com/ValveSoftware/openvr/wiki/IVRSystem::CaptureInputFocus).

Unfortunately if Carnival Games VR is requesting exclusive access to the controllers, as far as I'm aware, there just isn't anything I can do :(.

I'll see if I can buy it later and run some tests, but I suspect this is the case.

**Comment by Hotrian** [comment]
Picking up `Carnival Games VR` for $5 in the Steam Summer Sale :o. Will definitely test this out later and see what happens. If Carnival Games VR is using `CaptureInputFocus`, it would be the first game I've come across that uses it, so it might be interesting to test against.

I'll let you know if anything comes of it.

**Comment by Hotrian** [comment]
Sorry for never getting back to you. Will investigate ASAP, but I'm assuming `Carnival Games VR` is using `CaptureInputFocus` as `Pierhead Arcade` used to do this as well (though I believe they no longer make this call, I could be incorrect and would have to check again). If this is the case, there just isn't anything I can do as capturing exclusive access to the controllers is a built in part of SteamVR, and any application may do so. Changing this would require changes in SteamVR.

**Comment by Hotrian** [comment]
I forgot to address this one on GitHub, but Valve ultimately removed the CaptureInputFocus API since games were using it incorrectly, and this issue no longer exists.
