### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by CMDR-Helbram** [Hotrian/OVRdrop-Public#55]
System:  ASUS G752VS
HMD: Samsung Odyssey WMR
Crashed occurs before any game has been loaded

[error.log](https://github.com/Hotrian/OVRdrop-Public/files/2321164/error.log)
[output_log.txt](https://github.com/Hotrian/OVRdrop-Public/files/2321165/output_log.txt)

**Comment by Hotrian** [comment]
Sorry for the delay. It seems Sonic Studio 2 is causing an issue which causes OVRdrop to crash. Could you try closing Sonic Studio 2 temporarily (or at least disable the OSD if that is possible) to confirm?

**Comment by CMDR-Helbram** [comment]
Can confirm that closing Sonic Studio 2 before loading anything else seems to have done the trick,
will there possibly be a fix for this in the future or will I just have to keep closing it down after start up?

Cheers in advance.

**Comment by Hotrian** [comment]
I’m not sure there’s anything I can do to fix it. SS2OSD seems to be doing something weird to the stack, and it seems like this application just causes some games and other applications to crash :(.

**Comment by CMDR-Helbram** [comment]
Thank you for looking at it anyways and finding the application that was at fault I will just have to remember to disable SS2 when I run OVRdrop. Still in my opinion this is the best program for VR and was well worth the purchase.
