### ISSUE TITLE
Capture window freezes whenever you look directly backwards.

### ISSUE THREAD

**Issue by EternalLionZeke** [Hotrian/OVRdrop-Public#57]
I have my room set up to face away from my screen when I'm standing, but I face "backwards" when I'm sitting down. 

Looking up and down fixes the issue, but when I look back to my center the window stops refreshing.

I can see the mouse moving on top of the frozen window, but that's the only thing moving.

**Comment by Hotrian** [comment]
Could you please try the [latest version](https://github.com/Hotrian/OVRdrop-Public/wiki/Accessing-Alternative-Builds)? I seem to recall this was a bug I fixed at some point.
