### ISSUE TITLE
Keyboard input stops working

### ISSUE THREAD

**Issue by ArmEagle** [Hotrian/OVRdrop-Public#62]
This is something I've seen happen regularly lately.  (v1.0.5)

The hotkey to toggle the overlay sometimes stops working. Though can also run fine for hours.
If it has stopped I can (take off the Vive) and in OVRdrop click "Hotkey Settings" and start  to change the "Toggle Overlay" key. But whatever key I press; nothing is registered.

I am having regular other VR problems though. So it's very well possible that this isn't directly an OVRdrop issue. But if you have any suggestions of a log file to look into, then I'm all ears.

SteamVR 1.2.10
HTC Vive Pro (now for a few weeks)
Windows 10

My problems with SteamVR/Vive (Pro) is that often I get the -202, and -203 errors. With heavy display and audio output stutter/pauses. But at some point I manage to tame the beast and can play Elite Dangerous for hours. I still have no idea what the trick is that makes those issues to cease.

**Comment by Hotrian** [comment]
Hmm I haven’t heard of this one yet. 

The log file is `output_log.txt`, located inside the OVRdrop_data folder, next to the OVRdrop exe. The log is cleared on each restart, so you need to reproduce the issue before attaching the log here.
