### ISSUE TITLE
USB bus slowed down with OVRdrop

### ISSUE THREAD

**Issue by cdnstig** [Hotrian/OVRdrop-Public#63]
In general the mouse appears to slow down and become unresponsive. I use a Stream Deck to type text into a terminal window for flying in X-PLane. Without OVRdrop, this typing is almost instantaneous, however after launching OVRdrop, the text may take 3 - 4 seconds to type out. If necessary I can screen record to show the difference.

**Comment by Hotrian** [comment]
Hmm I'm not sure what could be causing that -- OVRdrop doesn't do anything with USB in specific, although Unity of course does interface with some USB devices such as gamepads.

Could you post your `output_log.txt`? It's inside the `OVRdrop_data` folder, next to the `OVRdrop.exe`.

**Comment by cdnstig** [comment]
[output_log.txt](https://github.com/Hotrian/OVRdrop-Public/files/2826062/output_log.txt)

Here ya go

**Comment by cdnstig** [comment]
No CPU (16%) and GPU (35%) seem to be fine. Thanks for the Sonic Studios tip

**Comment by cdnstig** [comment]
[Slow Typing.zip](https://github.com/Hotrian/OVRdrop-Public/files/2826079/Slow.Typing.zip)

**Comment by cdnstig** [comment]
Here is a quick video. You can see the difference in the typing speed from launching OVRdrop

**Comment by Hotrian** [comment]
Could you set OVRdrop's capture rate higher? That old version of OVRdrop seems to drop application FPS with capture rate; the newer versions won't drop below 60 so the VR experience (and things such as the keyboard stack) are not delayed - they only drop the capture rate.

If raising the FPS fixes the issue, I suggest [jumping on a newer build](https://github.com/Hotrian/OVRdrop-Public/wiki/Accessing-Alternative-Builds) which should solve the issue.

**Comment by cdnstig** [comment]
Interesting. It did make it better, but not quite as fast as off. I had turned it down to 15fps and then 1 hoping to increase performance, but using less resources. I'll try the newer build and see.

**Comment by cdnstig** [comment]
What build should I try?

**Comment by Hotrian** [comment]
The latest one is probably fine, although it seems p26 is the most stable right now as some users are reporting an issue with being able to click the side buttons.

**Comment by cdnstig** [comment]
Awesome. The speed improvement is enough to not be noticeable in X-Plane for my purposes. I didn't see a speed improvement in p26, but it may have been small enough to not see. Thanks so much for the quick help today. You can mark this as resolved. Increasing the FPS helped improve the USB bus speed, or whatever was plaguing performance. Please mark as resolved.
