### ISSUE TITLE
Nothing will work!

### ISSUE THREAD

**Issue by THEDESAMATER** [Hotrian/OVRdrop-Public#65]
![broken](https://user-images.githubusercontent.com/15834269/55347186-0ebebc80-54ac-11e9-9639-de9801e4e126.png)
the application worked first time i launched it but now will not work at all i can only get a sign to appear that says steam vr and the application is continusly duplicationg time to put your vr headset on, i have tried all methods of compatibility and running as admin aswell as trying the beta but nothing works

**Comment by Hotrian** [comment]
Are you the same person who emailed me?

Could you attach the output_log.txt, located in the OVRdrop_data folder?
