### ISSUE TITLE
Any help for an aspiring fellow Overlay dev?

### ISSUE THREAD

**Issue by Hokage3211** [Hotrian/OVRdrop-Public#70]
I'm attempting to make an overlay for steam that will be hopefully very useful to a lot of people using steamVR desktop viewing, I'd rather not say exactly what until I have a more solid finished product, but I'm having trouble with the new steamVR unity plugin disabling actions/translocation of the hands in my simulation whenever I open the steamVR dashboard, do you have any feedback on what might be causing this and how to fix it? Essentially the overlay is simulating hands inside of the unity scene using the player prefab for steamVR unity plugin, but the hands stop moving or showing inputs when the dashboard is opened in VR. Any advice? Hopefully this is maybe something you already came across in your overlay application?

**Comment by Hotrian** [comment]
Sorry I haven’t had this issue in specific so I wouldn’t be much help here. The SteamVR Dashboard itself does block input and certain event polling while open, but there are other calls you can make if you’re a dashboard overlay that you can look into (mobile right now so finding them could prove tricky).

**Comment by Hokage3211** [comment]
It's not mounted to the dashboard sadly (unless I'm not understanding what you mean) it's just an overlay like yours, that is in steamVR on it's own, but I do see that I can get the position of the headset and controllers at all times using NewPoses.AddListener, I'm mostly now looking for the finger curls/estimated finger positions, and SteamVR_Input.GetSkeletonAction is stopped when the dashboard is open. Does pose also talk about finger positioning? This new steam 2.0 update is a huge mess of vague unehelpful names and poor separated documentation.

**Comment by Hokage3211** [comment]
**Edit: Also, apparently NewPoses does not have a reliable array order, and none of the populated data has identifiers to them, at least not that I can find.

**Comment by Hokage3211** [comment]
Alright, I've gotten the tracking to work by going through OpenVR and getting the tracking data through that, but I've not been able to find a reliable way to get the controller inputs, as getControllerState is not returning axis values, only zeros, I don't expect you to help because you said yourself that you haven't ran into any situation like this, but thought I would update the issue to my current situation
