### ISSUE TITLE
OVRdrop window not rendering correctly in VR.

### ISSUE THREAD

**Issue by LukeTyWalker** [Hotrian/OVRdrop-Public#9]
I recently purchased OVRdrop from Steam and tested it out on my VR setup at home.  It worked great on this setup.  I bought it for my work VR station but when I ran it on that setup, the window doesn't display correctly.  All that shows up in VR is a couple of windows with nothing on them (generally just a white window and a larger, blue, semi transparent window)  I rebooted the PC and messed around with settings in OVR drop but none of that fixed the issue.  It may be something I am doing wrong or maybe its something with the differences in the configurations.

My home VR setup is:
HTC Vive
Nvidia GTX 1080
Windows 10 Professional

My work VR setup is:
HTC Vive
Nvidia Quadro P6000
Windows 7 Professional

Could the issue be with the Quadro drivers or perhaps windows 7?

I am hoping to use OVRdrop on my work VR setup with a CAD VR product called Visionary Render by Virtalis.  I don't know if it will work but I want to try and see if it will so I can display webex, videoconference feeds, etc into Visionary Render.  Visionary Render does not do any of that but perhaps your software would allow me to do this.  Right now, I can't even get the OVR drop to display in the VR headset in the normal Vive window (before I even launch Visionary Render...basically the "This is Real" lobby scene you see when you first put on the headset)

Any guidance you can give me would be greatly appreciated.

**Comment by LukeTyWalker** [comment]
[OVRDrop Window Not Displaying Properly.zip](https://github.com/Hotrian/OVRdrop-Public/files/891418/OVRDrop.Window.Not.Displaying.Properly.zip)

Here is a video where I show how the window does not display properly in VR.
I tried to use OVRDrop in Virtalis Visionary Render and it shows up inside the VR environment but has the same issue with not displaying the OVRDrop window properly.

Please help.  I think I am going to love this tool once I get it working.

**Comment by Hotrian** [comment]
Unfortunately this doesn't work on Windows 7 because the capture API didn't exist until Windows 8. 

If you check the minimum requirements it says 'Windows 7 not supported due to technical limitations' which unfortunately is the case here :(.

**Comment by LukeTyWalker** [comment]
Ahh.
Ok.
That’s a bummer.
Maybe I will try to migrate my work VR system over to Windows 10.
Thanks
Ty
